### ISSUE TITLE
NameError: uninitialized constant Dispatcher

### ISSUE THREAD

**Issue by hexistore** [alexpalyan/redmine_repository_control#1]
rake aborted!
NameError: uninitialized constant Dispatcher
/data/redmine/plugins/redmine_repository_control/init.rb:3:in `<top (required)>'
/data/redmine/lib/redmine/plugin.rb:155:in`block in load'
/data/redmine/lib/redmine/plugin.rb:146:in `each'
/data/redmine/lib/redmine/plugin.rb:146:in`load'
/data/redmine/config/initializers/30-redmine.rb:21:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:652:in`block in load_config_initializer'
/usr/local/rvm/gems/ruby-2.1.5/gems/activesupport-4.2.0/lib/active_support/notifications.rb:166:in `instrument'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:651:in`load_config_initializer'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:616:in `block (2 levels) in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:615:in`each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/engine.rb:615:in `block in <class:Engine>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in`instance_exec'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:55:in`block in run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:44:in `each'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:44:in`tsort_each_child'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:352:in`initialize!'
/data/redmine/config/environment.rb:14:in `<top (required)>'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:328:in`require_environment!'
/usr/local/rvm/gems/ruby-2.1.5/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in`eval'
/usr/local/rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => redmine:plugins:migrate => environment
(See full trace by running task with --trace)

**Comment by alexpalyan** [comment]
I'm sorry but this project is unsupported. You may use GIT version control with jbox-web/redmine_git_hosting project.

**Comment by hexistore** [comment]
ok，thanks
